#This is the makefile for the client/server talk program
#The following line is used to compile the server program
#it will produce an executable called serv that can be 
#executed using ./serv
serv: tcpserv04.c
	cc -o serv tcpserv04.c
#The following line is used to compile the clinet program
#it will produce an executable called cli that can be
#executed using ./cli 
cli: tcpcli01.c
	cc -o cli tcpcli01.c
